name: Test on Dev

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Run Rust tests
      run: cargo test --workspace

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python dependencies and package
      run: |
        pip install pytest torch huggingface_hub tqdm
        pip install .

    - name: Run Python tests
      run: pytest tests/
